token:
hostname: workspace.darwinbox.com

checkin:
  locationType: # 1 for Office, 2 for Home, 3 for Field Duty
  message:
  latlong:

checkout:
  locationType:
  message:
  latlong:

scheduler:
  checkin: 09:00
  checkout: 17:30
